version: '3.8'

services:
  api:
    image: rust:latest
    volumes:
      - ../game:/game  # Mount game workspace
      - .:/web  # Mount web service
      - cargo_target:/web/target  # Use a separate target dir inside the container
    working_dir: /web
    command: ["/bin/sh", "-c", "apt update && apt install -y libudev-dev cmake g++ clang libasound2-dev mold && rustup component add rustc-codegen-cranelift && cargo install cargo-watch && cargo watch -x check -x run"]
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017"
    ports:
      - "8000:8000"

  mongo:
    image: mongo:latest
    volumes:
      - mongo_data:/data/db

volumes:
  cargo_target:
  mongo_data:

